- alias: 'Record sensors on GSheets'
  trigger:
    platform: time
    minutes: '/1'
    seconds: 00
  action:
    - service: shell_command.record_sensors
      data_template:
        sensor01: '{{states.sensor.dark_sky_temperature.state | float}}'
